//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Comments')
export class CommentsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  ThumbsUp: number;

  @Column('integer', { nullable: true })
  ThumbsDown: number;

  @Column('text', { nullable: true })
  Reply: string;
}
