//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Messages')
export class MessagesEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  Post: number;

  @Column('bool', { nullable: true })
  Delete: boolean;

  @Column('bool', { nullable: true })
  Share: boolean;

  @Column('text', { nullable: true })
  Reply: string;
}
