//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Pages')
export class PagesEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  Post: number;

  @Column('text', { nullable: true })
  Contact: string;

  @Column('bool', { nullable: true })
  RequestForLikes: boolean;
}
