//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Post')
export class PostEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  Likes: number;

  @Column('integer', { nullable: true })
  Comments: number;

  @Column('text', { nullable: true })
  Reactions: string;

  @Column('bool', { nullable: true })
  Share: boolean;

  @Column('bool', { nullable: true })
  Repost: boolean;
}
