//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Videos')
export class VideosEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('bool', { nullable: true })
  Share: boolean;

  @Column('bool', { nullable: true })
  Edit: boolean;

  @Column('bool', { nullable: true })
  Delete: boolean;

  @Column('integer', { nullable: true })
  Post: number;
}
