//Source code generated by AppGPT (www.appgpt.tech)
import { mergeTranslations } from 'ra-core';
import polyglotI18nProvider from 'ra-i18n-polyglot';
import enOriginal from 'ra-language-english';
import frOriginal from 'ra-language-french';

const enResources = {
  resources: {
    Post: {
      name: 'Post',
      fields: {
        Likes: 'Likes',
        Comments: 'Comments',
        Reactions: 'Reactions',
        Share: 'Share',
        Repost: 'Repost',
        id: 'id',
      },
    },
    Comments: {
      name: 'Comments',
      fields: {
        ThumbsUp: 'Thumbs Up',
        ThumbsDown: 'Thumbs Down',
        Reply: 'Reply',
        id: 'id',
      },
    },
    Groups: {
      name: 'Groups',
      fields: {
        Post: 'Post',
        Share: 'Share',
        Comment: 'Comment',
        Reply: 'Reply',
        Reacts: 'Reacts',
        id: 'id',
      },
    },
    Pages: {
      name: 'Pages',
      fields: {
        Post: 'Post',
        Contact: 'Contact',
        RequestForLikes: 'Request For Likes',
        id: 'id',
      },
    },
    Messages: {
      name: 'Messages',
      fields: {
        Post: 'Post',
        Delete: 'Delete',
        Share: 'Share',
        Reply: 'Reply',
        id: 'id',
      },
    },
    Videos: {
      name: 'Videos',
      fields: {
        Share: 'Share',
        Edit: 'Edit',
        Delete: 'Delete',
        Post: 'Post',
        id: 'id',
      },
    },
  },
};
const frResources = {
  resources: {
    Post: {
      name: 'Post (fr)',
      fields: {
        Likes: 'Likes (fr)',
        Comments: 'Comments (fr)',
        Reactions: 'Reactions (fr)',
        Share: 'Share (fr)',
        Repost: 'Repost (fr)',
        id: 'id',
      },
    },
    Comments: {
      name: 'Comments (fr)',
      fields: {
        ThumbsUp: 'Thumbs Up (fr)',
        ThumbsDown: 'Thumbs Down (fr)',
        Reply: 'Reply (fr)',
        id: 'id',
      },
    },
    Groups: {
      name: 'Groups (fr)',
      fields: {
        Post: 'Post (fr)',
        Share: 'Share (fr)',
        Comment: 'Comment (fr)',
        Reply: 'Reply (fr)',
        Reacts: 'Reacts (fr)',
        id: 'id',
      },
    },
    Pages: {
      name: 'Pages (fr)',
      fields: {
        Post: 'Post (fr)',
        Contact: 'Contact (fr)',
        RequestForLikes: 'Request For Likes (fr)',
        id: 'id',
      },
    },
    Messages: {
      name: 'Messages (fr)',
      fields: {
        Post: 'Post (fr)',
        Delete: 'Delete (fr)',
        Share: 'Share (fr)',
        Reply: 'Reply (fr)',
        id: 'id',
      },
    },
    Videos: {
      name: 'Videos (fr)',
      fields: {
        Share: 'Share (fr)',
        Edit: 'Edit (fr)',
        Delete: 'Delete (fr)',
        Post: 'Post (fr)',
        id: 'id',
      },
    },
  },
};

const en = mergeTranslations(enOriginal, enResources);
const fr = mergeTranslations(frOriginal, frResources);

const translations = { en, fr };
export const i18nProvider = polyglotI18nProvider(
  (locale) => translations[locale],
  'en', //default locale
  [
    { locale: 'en', name: 'English' },
    { locale: 'fr', name: 'Français' },
  ],
);
